### ISSUE TITLE
[Todo]: Пустая карточка на любой день

### ISSUE THREAD

**Issue by ManushovRodion** [ManushovRodion/foreign-language-assistant#18]
### # Название

Пустая карточка на любой день

### # Описание

Мы не можем создать карточку с группами, если пропустили день заполнения. Чтобы это решить надо реализовать функционал добавления пустой карточки.

### # Постановка

1. Наверху, перед списком добавить кнопку: "Создать карточку"
2. При нажатие на нее должно всплывать модульное окно в котором отображается:
   1.  Заголовок "Новая карточка"
   2. Под заголовком расположено краткое описание: "Создание пустой карточки на определенный день. Создать карточку можно тогда, когда на этот день нет карточки".
   3. Отображаем ряд с полями:
       1. Год: поле обязательно; имеет формат четырех цифр;
       2. Месяц: поле обязательно; имеет формат двух цифр; минимальное значение 1; максимальное значение 12;
       3. День: поле обязательно; имеет формат двух цифр; минимальное значение 1; максимальное значение допустимое на текущий месяц, если месяц не введен 31
    4. Кнопки
        1. Отменить/Закрыть
        2. Сохранить: заблокирована если поля не заполнены

### # Логика

1. Кнопка "Отменить/Закрыть" закрывает модульное окно без изменений
2. Кнопка "Сохранить" запускает поиск карточке с данной датой:
    1. Если не найдено - создает
    2. Если найдено - выводит сообщение, что с данной датой карточка создана. 

### # Устройство

- [X] PC
- [X] Phone
- [X] Table

### # Браузер

- [X] Chrome
- [X] Firefox
- [X] Safari
- [X] Edge

**Comment by ManushovRodion** [comment]
Результат тестирования:

- [x] Создается пустая карточка на определенный день
- [x] Есть указание минимального значения года
- [x] Есть указание минимального значения месяца
- [x] Есть указание максимального значения месяца
- [x] Есть указание минимального значения дня
- [ ] Есть указание максимального значения дня
- [ ] Ограничение в 4 символа для поля год
- [ ] Ограничение в 2 символа для поля месяц
- [ ] Ограничение в 2 символа для поля дня
- [ ] Примечание "Создание пустой карточки на определенный день. Создать карточку можно тогда, когда на этот день нет карточки"
