### ISSUE TITLE
[Todo]: Форма добавления групп

### ISSUE THREAD

**Issue by ManushovRodion** [ManushovRodion/foreign-language-assistant#6]
### # Название

Форма добавления групп

### # Описание

Необходимо реализовать функционал добавления групп для карточки

### # Скриншоты и Видео

![form](https://raw.githubusercontent.com/ManushovRodion/foreign-language-assistant/master/docs/files/form_add_group_modal_desktop_and_table.png)

![form](https://raw.githubusercontent.com/ManushovRodion/foreign-language-assistant/master/docs/files/form_add_group_modal_phone.png)

### # Постановка

1. Необходимо сделать тикеты: #4 #5 
2. Сделать модульное окно, в котором заполняется форма группы

![form](https://raw.githubusercontent.com/ManushovRodion/foreign-language-assistant/master/docs/files/form_add_group_desktop_and_table.png)

![form](https://raw.githubusercontent.com/ManushovRodion/foreign-language-assistant/master/docs/files/form_add_group_phone.png)

Форма:
- Title group - название группы
  - По умолчанию там отображается placeholder с надписью "название группы"
  - При нажатие можно ввести название группы
  - Не обязательное поле
  - В случае наличия заполняется из локальной базы
- Под заголовком отображается таблица, где первая колонка слово/фраза на иностранном, напротив на русском и в третей колонке кнопка удаления строки.
- Под фразами располагается поле с метками, которые перечисляются через запятую. По факту эту мультивыбор из ранее добавленных меток в базе + добавление новых
- Кнопка "Отменить/Закрыть" - выступает в качестве отмены изменений и закрытие окна
- Кнопка "сохранить" - сохраняет содержимое в базе. Если новая группа, то создает и сохраняет новую группу. Если нет фраз, то сообщаем, что надо добавить фразы
- Кнопка "удалить" - отображается когда группа редактируется. Позволяет удалить группу целиком.

В мобильной версии кнопки растягиваются по все ширине окна. Например если будет одна кнопка, то она будет занимать все место по ширине окна.

### # Логика

1. Модульное окно открывает по нажатию кнопки "добавить" из карточки или кнопки "изменить" из группы.
   - В случае если добавить - мы создаем новую группу
   - В случае изменить - мы подтягиваем данные по группе и изменяем текущую группу при необходимости.
2. Клик за пределами окна не дает каких либо действий
3. Когда создаем новую группу, то отображаем первый пустой ряд таблицы. Первый пустой ряд удалить нельзя в таком случае. После заполнения первого ряда отображаем второй пустой ряд и кнопки удаления для всех рядов
4. Если у нас не первый ряд или редактирование группы, то мы отображаем в конце пустой ряд для заполнения данных.

В базе у группы должны быть две даты:
- Дата создания
- Дата обновления

### # Устройство

- [X] PC
- [X] Phone
- [X] Table

### # Браузер

- [X] Chrome
- [X] Firefox
- [X] Safari
- [X] Edge

**Comment by ManushovRodion** [comment]
Результат тестирования:


- [x] Поле с заголовком
- [x] Наличие строк с добавлением данных
- [ ] Поле с добавлением меток.- 
        - Не работает на мобильном устройстве: не позволяет выбрать из списка метку
        - Не подтягиваются новые элементы меток, после создания группы, для новой группы
- [x] Кнопка "Отменить/Закрыть"
- [x] Кнопка "сохранить" 
- [x] Кнопка "удалить" 

Примечания, которые не указаны в тикете: 
- [x] можно создать пустую группу - в таком случаем отображаем надпись, что необходимо добавить элементы группы.

Доработки: 
- [ ] стиль кнопок в ряду немного заходит в низ
